### ISSUE TITLE
Single VFO mode dual VFO information overlayed by RF Gain Control 

### ISSUE THREAD

**Issue by jepotter224** [OEFW-community/RT-890-custom-firmware#122]
Hello

With the 2.1.8 pcb 2.1 installed on a Radtel RT-890 V2.1 board radio built 3-2024, I find that in VFO dual display and RX is active on VFO A and I switch to VFO single display mode that the VFO B channel information continues to also display with the VFO A RF Gain Control information over top of it. In single VFO display mode should the other VFO information be cleared before the RF Gain Control information is displayed? NOTE: only seen when receiving a signal.

![image000001 (8)](https://github.com/OEFW-community/RT-890-custom-firmware/assets/146049166/9b8bea5f-292a-4ccb-b37f-e71b2f4a780f)
![image000000 (15)](https://github.com/OEFW-community/RT-890-custom-firmware/assets/146049166/9149952d-c07c-49c3-a4e4-7be97a852d0c)

power on ht -> switch to VFO display (while in dual display) both VFO A & B display with last frequency settings shown -> wait for or cause a frequency displayed to received signal -> switch to VFO signal mode -> goto VFO B -> see RF Gain Control over laying the other VFO display information -> switch to other VFO to see same issue now on opposite VFO.

I hope this helps.

**Comment by reppad** [comment]
Hi @jepotter224,
Based on the screenshots, I think you are using M7OCM's fork. I believe they will be able to help you at https://github.com/M7OCM/890-II.
