### ISSUE TITLE
FW download not works, shows expired

### ISSUE THREAD

**Issue by zodoczi** [OEFW-community/RT-890-custom-firmware#125]
Hi, 

I tried to download the pre-built FW from actions but looks like its expired and I cannot download it in a brave browser, logged in into github.

![image](https://github.com/user-attachments/assets/fd6d12ac-98f7-4710-ac16-78ff9d5c5bb9)

Thanks,
ha7dcd

**Comment by reppad** [comment]
I've extended the retention period for artifacts and made it possible for us to manually regenerate them when they expire.
You can find the firmware in the latest run.
