### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by M7OCM** [OEFW-community/RT-890-custom-firmware#26]
Firstly excellent work guys, some really innovative ideas and useful additions.

A few minor issues noted, you maybe working on them but thought just in case?!

Compiled the latest version myself  and given it a new look. More on that another time.

Menu 24 Scan Resume, this  menu selection is corrupted with additional non related menu data like CTS/DCS, half a character/digit, plus formatting issues scrolling through the list. Doesn't negatively effect selections/operation though. Cosmetic. Tried some fixes but no joy.

When using the flashlight in single ch/VFO mode the AM Fix registers overlay the blank white screen. Fine in DW.

Repostioning AM, FM and SSB has led to the SQ/VO indicator overlaying the mode indication and persisting. The compromise I use on my custom versions is to keep the original posits, but reduce "SSB" to "SB". Visual improvement suggestion - no other impact.

Menu 11 Freq Step issues. Easy fix. Was missing 12.5K in the ui/menu.c file, this fixed problem with 0.01 kHz selection.

Using a long press shortcut key for Freq Detect ( I tested on "3" and "5") stops the ability to change mode or do a CTS scan via # and *. Works ok if Freq Detect selected by side key as normal. No doubt a confliction going on there.

Huge improvement over stock, keep up the good work. I'll continue torture testing!

Thanks

**Comment by reppad** [comment]
Thank you very much for this feedback, that's exactly what we need!
It is true that we have tortured the menus several times recently.
We've been watching all this!

**Comment by reppad** [comment]
I've already seen what you did with UI, I can't wait to see what's next 😃

**Comment by reppad** [comment]
Normally everything is corrected except for the problem with the frequency detector when it is launched via a numeric key, that one is a bit less obvious to fix.
In any case, you did great tests to find that out!

**Comment by M7OCM** [comment]
Thank you and you're very welcome. It was fun tracking down the code to change colors. I've held off updating the community builds as things are moving at a pace. Not sure if I can pull off  anything groundbreaking, working with two themes is a slight compromise but got some ideas I'm experienting with.

I'm a radio user at heart, so testing new features and finding issues is quite a rapid process. I'm no developer like you guys but am keen to learn as I go and certainly picked up a few things from you pros!

The preset channels iradio came up with is very odd. Why a user would want to dedicate all 4 sidekey functions seems awfully wasteful. A single button repeat press through the 4 channels seems more sensible, but what do I know?! ha

Suppose I better start working on  that orange theme!

**Comment by M7OCM** [comment]
![20231117_070351.jpg](https://github.com/OEFW-community/RT-890-custom-firmware/assets/128899149/782883ae-bd50-46ba-9bf9-051d669f4a90)

Seems a waste of a color screen!

![20231117_070508.jpg](https://github.com/OEFW-community/RT-890-custom-firmware/assets/128899149/daf69c38-226f-4793-8aac-ce36acad5874)

**Comment by M7OCM** [comment]
![20231117_070351.jpg](https://github.com/OEFW-community/RT-890-custom-firmware/assets/128899149/782883ae-bd50-46ba-9bf9-051d669f4a90)

Seems a waste of a color screen!

![20231117_070508.jpg](https://github.com/OEFW-community/RT-890-custom-firmware/assets/128899149/daf69c38-226f-4793-8aac-ce36acad5874)

 One thing leads to another lol

![20231117_092018.jpg](https://github.com/OEFW-community/RT-890-custom-firmware/assets/128899149/41e6d582-a246-4f0b-8c7f-27efd2716452)

[ui/gfx.c]

void UI_SetColors(uint8_t DarkMode)
{
	if (DarkMode) {
		COLOR_BACKGROUND = COLOR_RGB( 0,  0,  0);
		COLOR_FOREGROUND = COLOR_RGB(31, 63, 31);
	} else {
		**// COLOR_BACKGROUND = COLOR_RGB(31, 41, 0); OEM Orange
		// COLOR_BACKGROUND = COLOR_RGB(16, 45, 0); LCD Green
		// COLOR_BACKGROUND = COLOR_RGB(0, 24, 31); LCD Blue
		// COLOR_BACKGROUND = COLOR_RGB(16, 32, 16); LCD Grey**
		COLOR_BACKGROUND = COLOR_RGB(16, 45, 0);
		COLOR_FOREGROUND = COLOR_RGB( 0,  0,  0);
	}

**Comment by reppad** [comment]
> I'm a radio user at heart, so testing new features and finding issues is quite a rapid process. I'm no developer like you guys but am keen to learn as I go and certainly picked up a few things from you pros!

Do not hesitate if we can help.

> The preset channels iradio came up with is very odd. Why a user would want to dedicate all 4 sidekey functions seems awfully wasteful. A single button repeat press through the 4 channels seems more sensible, but what do I know?! ha

For the moment we are trying to keep the original behavior as much as possible but I agree.

> Suppose I better start working on that orange theme!

I like this one, I vote to call it RT-890(8) for those who will understand.

The others are nice too, it probably doesn't take up much space, it could surely be integrated as alternatives to the light theme in the menu

**Comment by M7OCM** [comment]
Thank you very much, there is one bit of code I can't track down (or missed somewhere?) and thats the dialog border color code (and the related horizontal line that appears here and there).

It can be set in CPS and Chirp but color selection is not the best and it'd be cool to code it in so it persists.

Thanks also for the fixes cool the scan resume menu looked a tricky one!!

Update
Disregard found a way! lol

**Comment by reppad** [comment]
> Thank you very much, there is one bit of code I can't track down (or missed somewhere?) and thats the dialog border color code (and the related horizontal line that appears here and there).

This value is `gSettings.BorderColor`, it can only be set from chirp/cps (for now). You can easily found where it is used with a global text search.

> Thanks also for the fixes cool the scan resume menu looked a tricky one!!

This value is a bit different as others settings to ensure all is working for users that comes from stock firmware.

**Comment by M7OCM** [comment]
Thanks, found it earlier all sorted 😁

**Comment by reppad** [comment]
I keep it open while we find the problem with the frequency detector keys.
