### ISSUE TITLE
Upper left screen artifact

### ISSUE THREAD

**Issue by M7OCM** [OEFW-community/RT-890-custom-firmware#28]
Hi Reppad, here's a weird one.

Switching betweem light theme and dark theme generates a rectangle (approx 17x2 pixels) in the uppermost left region of the screen.

As the actual screen is larger than the visible display there could well be more artifacts beneath the case bezel.

![20231119_075717.jpg](https://github.com/OEFW-community/RT-890-custom-firmware/assets/128899149/fbee4338-9208-4d4a-86b1-b7f75d011482)

See if you can recreate it.

Thank you 😀

**Comment by reppad** [comment]
It's cheating if you lean the radio to watch under the case. 😅
Well seen, most of the time the screen is only partially erased to speed up the display, it can create this kind of thing when changing background color, I will look as soon as I can.
Thank you for the feedback.

**Comment by M7OCM** [comment]
Ha ha yes it was a sneaky one!

Ah ok, always glad to learn its not a bug I've introduced. Makes total sense.

Fixes at your leisure 😀 no rush, gives me time to play radio 😂
