### ISSUE TITLE
Scan Lists

### ISSUE THREAD

**Issue by M7OCM** [OEFW-community/RT-890-custom-firmware#37]
This is a great feature and with 999 channels very much needed lol Currently playing with the scan operation. 

Issues

Note I use Sidekey 2 Short (SK2S) for scanning and sometimes #1. 

DW on and off Single VFO tested same behaviour.

Channels added to Chan in List 1 . Select List to Scan 1. Scan... Scan works ok (yay).

From a cold start boot, selecting scan via both methods above, results in no scanning. Back to menu select List to Scan 1... 1, scan, and scan works ok. if SK2S or #1 is pressed scan stops (thats ok), but it doesn't restart scanning.

I think these Qs might be asked in future - so I'll ask now lolol. 

*** ignore Can you or are there plans to link Scan Banks/Lists? ie scan S1, S5, S8? 

Are the lists limited or totally dynamic, eg 150 in one list 10 in another, 50 in the next and so on (similar to how Uniden did the UBC3500XLT mem allocation).

I'll add more banks and see what happens 👍

**Comment by M7OCM** [comment]
Just had a thought - be rather good if the List to Scan # corresponded with quick access #1-8 via menu selection (not a request just an idea, maybe useful to someone).

**Comment by M7OCM** [comment]
Ok added channels to list 8. Scanning 8 works, press scan again, scan all (cool). Scan again stop nothing scanning.

Didn't realise but it appears there has to be some channels in the next bank to continue. Ok makes sense now. As a feature goes think it needs to jump empty lists  and just link banks/lists. I see where this is going so excuse the first post as I didn't realise that press scan twice it then scans all, which is excellent.

**Comment by reppad** [comment]
> Channels added to Chan in List 1 . Select List to Scan 1. Scan... Scan works ok (yay).
> 
> From a cold start boot, selecting scan via both methods above, results in no scanning. Back to menu select List to Scan 1... 1, scan, and scan works ok. if SK2S or #1 is pressed scan stops (thats ok), but it doesn't restart scanning.

When you press a key mapped to scan action during a scan, it not stop the scan, it select the next scanlist (1,2,3,4,5,6,7,8,*,1,2…) and continue scanning.
If this select an empty scanlist, the scan just stop but the empty scanlist stay selected until you change it in menu (you probably see the scanlist number appearing briefly in statusbar when trying to restart scan). I have to find a way to avoid that, maybe pass over empty scanlist ?

> I think these Qs might be asked in future - so I'll ask now lolol. Can you or are there plans to link Scan Banks/Lists? ie scan SB1, SB5, SB8? 

I do not plan to cycle scan lists because it would be like having a single list, but as said previously you can jump to next scanlist during scan using scan action.

> Are the lists limited or totally dynamic, eg 150 in one list 10 in another, 50 in the next and so on (similar to how Uniden did the UBC3500XLT mem allocation).

Totally dynamic, you can add all 999 channels in each of 8 lists if you’re masochist 😅

Many thanks for testing, this helps a lot !

**Comment by reppad** [comment]
> Just had a thought - be rather good if the List to Scan # corresponded with quick access #1-8 via menu selection (not a request just an idea, maybe useful to someone).

Good idea, we could add actions that launch the scan for a predefined list instead of the current list, I note that for later!

**Comment by reppad** [comment]
> Didn't realise but it appears there has to be some channels in the next bank to continue. Ok makes sense now. As a feature goes think it needs to jump empty lists and just link banks/lists. I see where this is going so excuse the first post as I didn't realise that press scan twice it then scans all, which is excellent.

Don't apologize, you're right, we need a user guide!

**Comment by reppad** [comment]
Most of these points have been corrected in PR #35.
I haven't yet implemented shortcuts to launch a predefined scanlist directly, I think I'll do that separately.
