### ISSUE TITLE
DCS normal/inverted missmatch

### ISSUE THREAD

**Issue by Xygen** [OEFW-community/RT-890-custom-firmware#63]
When trying to use DCS together with a K5(8) running Nunu 19.6, I need to either use Normal DCS on the K5 and Inverted DCS on the 890 or Inverted DCS on the K5 and Normal DCS on the 890.
According to Kamil two K5 work fine.
So it's either Kamils Nunu v19.6 or with OEFW, which is having a mismatch between normal and inverted DCS.
I'm happy to provide any more information.
The 890 is running 63b1577.

**Comment by Xygen** [comment]
I'm testing with a Yaesu FT5, which has a DCS scanner, and it seems RX DCS and TX DCS are mixed... You can see that also in the display of the 890 if you put different codes in for RX and TX.

**Comment by Xygen** [comment]
The issue must be in the RxDCS part of the 890. It requires inverted when normal has been configured in the 890, and requires normal when inverted has been configured to open squelch.
The K5 is sending that correctly, as it has been tested with the DCS scanner of a FT5.
Also the TxDCS part of the 890 is working correctly when tested with a FT5.

**Comment by reppad** [comment]
Hi Xygen,

I just tested and I have the same behavior.
The [code ](https://github.com/OEFW-community/RT-890-custom-firmware/blob/63b1577fccb074890d1950f817e0a184b562b82c/task/rssi.c#L76)that check the polarity of the DCS when RX seems OK, maybe we have an inversion between what is displayed and what is stored or something like that.
I'll dig deeper soon.

Thanks for this report !

**Comment by reppad** [comment]
I took a moment to look around and identified a few elements for further analysis:
- the parameters entered and saved are indeed those displayed
- reading the register and interpreting the value seems to comply with the specification
- the value read from the register is the opposite of the one expected, for some unknown reason

Bit 14 of register 0C should be set to 1 when a positive CDCSS is received and bit 15 when a negative CDCSS is received.
In fact, the opposite happens.

We could simply reverse the logic, but I'd like to understand what's going on, given that the code seems to be doing what it should.

**Comment by DualTachyon** [comment]
https://github.com/OEFW-community/RT-890-custom-firmware/commit/f24641c3fa3d0911585f24d2319c9028bd5e00b8#commitcomment-138752218

**Comment by xawen** [comment]
Marcos tracked the issue back to the alternative squelch system I added some time ago (since the stock squelch relies on calibration data in SPI memory that Radtel didn't bother to set to anything useful).  Turns out I was setting bit 8 of register 0x4E to 0.  It is set to 1 by the stock OEFW firmware.  This bit is undocumented in the BK4819 docs.  But, preserving the 1 fixed the inversion issue.

**Comment by reppad** [comment]
Well done to have found this, we could have searched for a long time!

**Comment by xawen** [comment]
Closing as resolved.  e321978 pushed with fix.
