### ISSUE TITLE
Frequency detector always detects DCS as custom 23bits code.

### ISSUE THREAD

**Issue by ea7hjb** [OEFW-community/RT-890-custom-firmware#70]
Hi!

I'm reporting this bug here, as I did in the original OEFW GitHub (https://github.com/DualTachyon/radtel-rt-890-oefw/issues/13).

Basically, the scanner works well but it will ALWAYS detect a standard DCS as a custom 23 bit code. Yes, DCS are 23 bit codes, and any combination between 000 and 777 is possible, but standariced DCS coded (straight or inverted) should be showed as their "normal accepted" form, not like custom ones.

For those who want to read a bit more from DCS (and other stuff), this lost webpage is a gold mine: https://web.archive.org/web/20190731110827/http://onfreq.com/syntorx/dcs.html

I have pro gear available to test all kind of standard and custom CTCSS and DCS codes at will.

I think this bug deserves some love because it is the last thing missing to be fixed from the original OEFW, and that would make the great reverse engineering job of DualTachyon perfect, completed.

**Comment by xawen** [comment]
Resolved by 7d7bab8,
