### ISSUE TITLE
Freq Detect/Reg Overlay

### ISSUE THREAD

**Issue by M7OCM** [OEFW-community/RT-890-custom-firmware#77]
Disregard not an issue with OEFWCOM 👍 Will close.

Will update this as it is an issue (in commit f24641c)

**Comment by M7OCM** [comment]
Xawen kindly pointed me in the direction for fixes to an overlay issue I'm experiencing with Freq Detect, yesterday.

At the time I thought it was just an issue in my firmware revision. Tried a previous OEFWCOM build (pre dated issue); that was okay, but the very latest does indeed have 2 issues, well 3 as the battery icon overlays flashlight too.

The AGC Mode registers overlay the Freq Display in Single ch/vfo mode; the same happens when scanning while FM radio is active.

I'll pop some pics up in a sec.

Incidentally, I tried numerous ways/code locations to inhibit the reg/freq detect issue I'm having but to no avail

eg task/battery.c  in the UI_DrawVoltage code etc

&& !gScannerMode
&& !gFrequencyDetector == 0

void this void that various iterations ;-)

**Comment by M7OCM** [comment]
![20240225_130105.jpg](https://github.com/OEFW-community/RT-890-custom-firmware/assets/128899149/91735ce9-6e26-4759-be79-46d174fdc675)

![20240225_130051.jpg](https://github.com/OEFW-community/RT-890-custom-firmware/assets/128899149/172de130-821b-487a-94ed-d599b0803c8d)

![20240225_130035.jpg](https://github.com/OEFW-community/RT-890-custom-firmware/assets/128899149/1985ef03-df36-4114-b496-d838c65aefe2)

**Comment by reppad** [comment]
Hi Olaid,
Good catch, I had never tried to run a scan while the FM radio was on 😊
I'll try to have a look to the frequency detector too.
For the flashlight I know it's not very aesthetic but I left the contents of the battery voluntarily to keep the information, I should probably take the time to display its outline in black!

**Comment by M7OCM** [comment]
> Hi Olaid,
> Good catch, I had never tried to run a scan while the FM radio was on 😊
> I'll try to have a look to the frequency detector too.
> For the flashlight I know it's not very aesthetic but I left the contents of the battery voluntarily to keep the information, I should probably take the time to display its outline in black!

Thanks Reppad and hope all is well? Ah I see, re the battery icon just thought I'd mention it 😀 ha yes the outline, quite like it bit of a Commodore C16 retro look to it 😅

Yes the scan while listen to FM is really cool works very well, especially nice feature when comms are quiet. Sounds good compared to K5 🙉

**Comment by reppad** [comment]
Apart from the lack of time, everything is fine, hope you too?
I just deleted the possibility of launching a scan from the FM radio mode in the dev branch 😅 I didn't think we would want to do it but you're right, I'm going to change that!
It complicates things at the UI level, I have to think about it!

**Comment by reppad** [comment]
Hi @M7OCM, 
I've tried running the scanner while the FM radio is on and it doesn't work, you can see the channels scrolling in overlay but it never stops when there's a signal.

Here's how I test it:
* starting the FM radio
* scanner start-up from a side button
* TX from another radio
* nothing happens, the FM music stays on and the channels scroll (of course it works when I scan without the FM radio)

Maybe I'm not using it the same way as you, can you confirm that [it works on the `main` branch](https://github.com/OEFW-community/RT-890-custom-firmware/actions/runs/8040652494), if not which commit does it work on to your knowledge?

**Comment by M7OCM** [comment]
> Hi @M7OCM, 
> I've tried running the scanner while the FM radio is on and it doesn't work, you can see the channels scrolling in overlay but it never stops when there's a signal.
> 
> Here's how I test it:
> * starting the FM radio
> * scanner start-up from a side button
> * TX from another radio
> * nothing happens, the FM music stays on and the channels scroll (of course it works when I scan without the FM radio)
> 
> Maybe I'm not using it the same way as you, can you confirm that [it works on the `main` branch](https://github.com/OEFW-community/RT-890-custom-firmware/actions/runs/8040652494), if not which commit does it work on to your knowledge?

Hi R, thanks yes all ok here, bit tired to be honest too many late nights/early starts!

Ok I will download asap, arhh right, FM standby needs to be on otherwise it will scan for eternity, I should have mentioned it. 

Hmmm I honestly couldn't say, all I do know is stock was okay (+OEFW if memory serves me correctly) though it scanned in the background no overlay. I'm sure I'd have noticed it early on even after the single display regs were added.

I take a look through and load up a random see if we can ascertain when it became a problem.

**Comment by M7OCM** [comment]
Hi R just been testing the fix-overlay branch.

Freq Detect works okay with a caveat. A button combo can put it under stress. Namely, press FM turning on FMB, then press (in my case Side key 1 long) to start Freq Detect.

When a signal gets RX, this happens...
![20240226_110700.jpg](https://github.com/OEFW-community/RT-890-custom-firmware/assets/128899149/4f62e984-bceb-4c46-b42d-b5c601f1f2b4)

Upon Exit this happens...
![20240226_110751.jpg](https://github.com/OEFW-community/RT-890-custom-firmware/assets/128899149/01ca0263-acc9-4ef1-8ce9-329dd223eb62)

... overlays the Freq Detect.

You may want to try this with Reg Edit =1 in makefile. Might be exactly the same result but you never know. Seems to be something to do with the interaction between single display and regos somewhere, I spent 6+ hours wading through code but can't figure out where it is😅.

**Comment by M7OCM** [comment]
You may note that the CB name tag got forwarded to VFO in the process no big deal.


UPDATE 

I'll get back to testing later, want to fully explore the FM radio thing without other distractions my end 😉

**Comment by M7OCM** [comment]
Just testing to destruction and during said exercise this got me thinking...

![20240226_163806.jpg](https://github.com/OEFW-community/RT-890-custom-firmware/assets/128899149/c732413b-51e3-4724-af95-373e52bc22f2)

... launching Freq Detect into the window above the freq is actually rather cool. Not in the remit I know but 🤔 Get rid of the lousy bitmaps in the process win win 😅

**Comment by reppad** [comment]
I had to slow down the speed of the scan mode when launched from the FM radio because the fact that the VFO is not redrawn each time does not leave enough time to catch incoming signals 🤯

@M7OCM I haven't looked at your latest tortures yet, but the first 2 overlays should be fixed.
Could you check whether this is the case for you and whether the scan from FMB works correctly for your use?
[PR](https://github.com/OEFW-community/RT-890-custom-firmware/pull/80)
[Build](https://github.com/OEFW-community/RT-890-custom-firmware/actions/runs/8078265430)

**Comment by M7OCM** [comment]
> I had to slow down the speed of the scan mode when launched from the FM radio because the fact that the VFO is not redrawn each time does not leave enough time to catch incoming signals 🤯
> 
> @M7OCM I haven't looked at your latest tortures yet, but the first 2 overlays should be fixed. Could you check whether this is the case for you and whether the scan from FMB works correctly for your use? [PR](https://github.com/OEFW-community/RT-890-custom-firmware/pull/80) [Build](https://github.com/OEFW-community/RT-890-custom-firmware/actions/runs/8078265430)

Thanks R, I'll compile now and give it a test (a kinder one lol), great stuff!

Incidentally in my version, I added a bit of code to force freq detect into dual display on stop, even if started in single mode. as that how I prefer it, I'll comment it should anyone wish to change back:

gFrequencyDetectMode = false;
**gSettings.DualDisplay = 1**
SCREEN_TurnOn();

Onwards. Later

**Comment by M7OCM** [comment]
Works as advertised. Not trying to kill it.  Really clever fix 😍👍 Great to learn new tricks.

I suppose the best solution for my torture test button push combo is to prevent Freq Detect ops while FMB is active?

Wow, OEFW 890 forum is on fire! 

I honestly think v2.1.0 is my last update I spend more time on fw than listening 😂

**Comment by reppad** [comment]
Thanks, you have a talent for finding this kind of bug!
I've prevented the frequency detector from running when the FM radio is on, so I think we're good on this issue?

**Comment by M7OCM** [comment]
Yep I sure do!

Yes you have done a sterling job thank you close this when you are ready :-)
