### ISSUE TITLE
Display overlay Flashlight background

### ISSUE THREAD

**Issue by M7OCM** [OEFW-community/RT-890-custom-firmware#88]
eek, another one of these Reppad sorry!

If Flashlight operation is interrupted by a RX signal the display overlays the white background.

Not exactly a priority :-)

**Comment by reppad** [comment]
Now that you mention it, I'm not really surprised :hand_over_mouth:
Thanks for pointing it out, I'll take care of it as soon as possible.

**Comment by M7OCM** [comment]
> Now that you mention it, I'm not really surprised :hand_over_mouth:
> Thanks for pointing it out, I'll take care of it as soon as possible.

😂 understand completely, overlaying is enemy #1

Thanks R

**Comment by reppad** [comment]
It should be solved, I took the opportunity to add the battery outline in flashlight mode.

**Comment by 9A6BA** [comment]
Any chance to put CCIR and ZVEI on it???
