### ISSUE TITLE
Add bandwidth toggle in long press shortcuts

### ISSUE THREAD

**Issue by SteefW** [OEFW-community/RT-890-custom-firmware#95]
Hi guys!
What an incredible work when looking through all the issues and requests!
I tried to program change VFO key (the red Exit/A/B) to another key and tried the # key (for changing from channel to freq mode) to program with a numerous key as well. If I have looked well enough I see that these keys cannot be programmed. Is that right? Could these two keys be added to the programmable keys or would that be not possible or too complicated?
Thanks so much anyway!

**Comment by reppad** [comment]
Hi Steef,

The functions you describe are triggered by a short press.
All keys are configurable except arrows, but for long press action.

For the moment we do not propose to modify the essential functions of the keys (short press).
I imagine that it would be technically possible but it would take up a lot of space in the memory compared to the interest it presents, and users would risk making their radio unusable by changing the behavior of the EXIT key for example.

Thanks for your interest !

**Comment by SteefW** [comment]
Hi reppad,
Thanks for your clear explanation. I understand. Just trying to 'make' 890 as much as possible same keys as K5...
There is however 1 other important keys that has no short push if i'm right: i cannot findbandwidth to be programmed.
Would bandwidth be possible to program on a longpress (eg number) key ?

**Comment by reppad** [comment]
Yes, you can't change the bandwidth with a long press.
It's something we can do quite easily, I'm renaming this issue accordingly so that I or anyone else interested can do it.
Thanks for the suggestion!

**Comment by reppad** [comment]
@SteefW, @jcalado made your wish come true 💪
