### ISSUE TITLE
LTO breaks RX meter and vox

### ISSUE THREAD

**Issue by xawen** [OEFW-community/RT-890-custom-firmware#98]
Currently enabling LTO in Makefile breaks the RX mic volume level meter and causes VOX mode to get stuck transmitting.

Dev details: This appears to be because LTO causes reads of register 0x64 (using the function BK4819_ReadRegister(0x64)) to come back with incorrect high values.

**Comment by bricky149** [comment]
I recall a similar experience with the K5, the conclusion being LTO code was running faster than the GPIO pins could settle. As a result, building the stock firmware with LTO made flash reads and writes unreliable. I would suggest adding a 1µs delay after changing pin states in bsp/gpio.c (thinking gpio_bits_set and gpio_bits_reset funcs ATM) to allow them to settle before carrying on execution. Function calls add enough delay without needing to add more.

**Comment by xawen** [comment]
> I recall a similar experience with the K5, the conclusion being LTO code was running faster than the GPIO pins could settle. As a result, building the stock firmware with LTO made flash reads and writes unreliable. I would suggest adding a 1µs delay after changing pin states in bsp/gpio.c (thinking gpio_bits_set and gpio_bits_reset funcs ATM) to allow them to settle before carrying on execution. Function calls add enough delay without needing to add more.

Good tip, thank you.  Doing it globally in the gpio_bits_set and gpio_bits_reset functions makes the radio extremely laggy.  BUT it does fix the meter issue.  I will try to narrow down where to better place the delays to fix those without lagging out the entire radio.

**Comment by bricky149** [comment]
> Good tip, thank you. Doing it globally in the gpio_bits_set and gpio_bits_reset functions makes the radio extremely laggy. BUT it does fix the meter issue. I will try to narrow down where to better place the delays to fix those without lagging out the entire radio.

I had the same experience. I ended up splitting the single 10-tick delays into five 2-tick delays in BK4819_ReadRegister and BK4819_WriteRegister, after the grouped GPIO calls and any I2C call as they manipulate pins. I can't test to make sure but it doesn't seem to have any bad side-effects.

Thanks for looking at this. I got around to writing a RT-890 flasher today that works natively on my Linux system. I hope to make it public tomorrow (later today in my TZ).

**Comment by xawen** [comment]
> > Good tip, thank you. Doing it globally in the gpio_bits_set and gpio_bits_reset functions makes the radio extremely laggy. BUT it does fix the meter issue. I will try to narrow down where to better place the delays to fix those without lagging out the entire radio.
> 
> I had the same experience. I ended up splitting the single 10-tick delays into five 2-tick delays in BK4819_ReadRegister and BK4819_WriteRegister, after the grouped GPIO calls and any I2C call as they manipulate pins. I can't test to make sure but it doesn't seem to have any bad side-effects.
> 
> Thanks for looking at this. I got around to writing a RT-890 flasher today that works natively on my Linux system. I hope to make it public tomorrow (later today in my TZ).

Isolated delays in BK4819_ReadRegister and BK4819_WriteRegister didn't seem to help.  But I did find a subset of GPIO calls that seemed to be affected by LTO.  I isolated them with a delay in gpio_bits_set and gpio_bits_reset.  Changes are in 624167d,  This fixes the TX meter and Vox with no side effects that I have found so far.  Running with LTO enabled for a bit to see if I can find any other issues.

Also that's great news about the Linux version of the flasher.  Welcome to the party!

**Comment by xawen** [comment]
Fix pushed to main.  Closing issue as resolved.
