### ISSUE TITLE
Registers display over NOAA screen when Dual Display is disabled

### ISSUE THREAD

**Issue by xawen** [OEFW-community/RT-890-custom-firmware#99]
When dual VFO display is disabled, the register display incorrectly overlays the NOAA screen.

Dev details: The registers are drawn by the UI_DrawVoltage() function.  This function starts with an if statement that prevents the registers from being drawn unless the radio is on the main screen (gScreenMode == SCREEN_MAIN).  However, it appears that NOAA mode does not have it's own gScreenMode, so that variable stays on SCREEN_MAIN in NOAA mode.  Need to find a variable to identify NOAA mode and update that function.

**Comment by jcalado** [comment]
#102 should fix this

**Comment by xawen** [comment]
Issue resolved.
